---
sidebar: sidebar 
permalink: task-set-up-gcnv.html 
keywords: setup, set up, api, service account, requirements, permissions, google cloud netapp volumes, gcnv, bluexp. netapp console 
summary: Die NetApp Console benötigt Zugriff auf die Google Cloud NetApp Volumes -API und die richtigen Berechtigungen über ein Google Cloud-Dienstkonto. 
---
= Einrichten von Google Cloud NetApp Volumes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die NetApp Console benötigt die richtigen Berechtigungen über ein Google Cloud-Dienstkonto.

Führen Sie die folgenden Aufgaben aus, damit die NetApp Console auf Ihr Google Cloud-Projekt zugreifen kann.

* Wenn Sie noch kein bestehendes Servicekonto haben, erstellen Sie ein neues.
* Zugriff für Identitätsdiebstahl gewähren.
* Gewähren Sie die IAM-Rolle im freigegebenen Projekt.




== Einrichten eines Dienstkontos

. In der Google Cloud-Konsole https://console.cloud.google.com/iam-admin/serviceaccounts["Gehen Sie zur Seite „Dienstkonten“"^] .
. Klicken Sie auf *Projekt auswählen*, wählen Sie Ihr Projekt aus und klicken Sie auf *Öffnen*.
. Um ein Dienstkonto zu erstellen, gehen Sie wie folgt vor:
+
.. Klicken Sie auf *Dienstkonto erstellen*.
.. Geben Sie den Namen des Dienstkontos (freundlicher Anzeigename) und eine Beschreibung ein.
+
Die Google Cloud Console generiert basierend auf diesem Namen eine Dienstkonto-ID.  Bearbeiten Sie die ID bei Bedarf. Sie können die ID später nicht mehr ändern.

.. Klicken Sie auf *Erstellen und fortfahren*.
.. Wählen Sie in der Rollenliste die Rolle * Google Cloud NetApp Volumes Administrator* oder * Google Cloud NetApp Betrachter* aus.
.. Wählen Sie *Weiter*.
.. Gewähren Sie diesem Dienstkonto eine Identitätswechselberechtigung: credentials-sa@wf-production-netapp.iam.gserviceaccount.com. Weitere Einzelheiten finden Sie unter https://cloud.google.com/iam/docs/create-short-lived-credentials-direct#sa-credentials-jwt["Erstellen Sie ein selbstsigniertes JSON Web Token (JWT)"^] .
+
Das von NetApp betriebene Dienstkonto dient dazu, ein kurzlebiges Zugriffstoken anzufordern, mit dem Sie als dieses Dienstkonto agieren können, ohne Zugriff auf dessen privaten Schlüssel zu benötigen.

.. Klicken Sie unten auf der Seite auf *FERTIG* und fahren Sie mit dem nächsten Schritt fort.






== Gemeinsam genutzte VPC

Gehen Sie in jedem weiteren GCP-Projekt, das das Dienstkonto verwendet, wie folgt vor:

. Wählen Sie auf der _IAM-Seite_ das Shared VPC-Hostprojekt aus dem Projekt-Dropdown-Menü aus.
. Klicken Sie auf *Hauptbenutzer hinzufügen*.
. Geben Sie im Feld „Neue Auftraggeber“ die E-Mail-Adresse Ihres Dienstkontos ein.
. Wählen Sie im Dropdown-Menü „Rolle auswählen“ die Rolle * Google Cloud NetApp Volumes -Administrator* aus.
. Klicken Sie auf *Speichern*.


Ausführliche Schritte finden Sie in der Google Cloud-Dokumentation:

* link:https://cloud.google.com/iam/docs/creating-managing-service-accounts["Erstellen und Verwalten von Dienstkonten"^]
* link:https://cloud.google.com/iam/docs/roles-permissions/netapp["Rollen und Berechtigungen für Google Cloud NetApp Volumes"^]
* link:https://cloud.google.com/iam/docs/granting-changing-revoking-access["Gewähren, Ändern und Widerrufen des Zugriffs auf Ressourcen"^]




== Fehlerbehebung

Wenn ein Fehler auftritt, kann die Richtlinie *iam.disableCrossProjectServiceAccountUsage* erzwungen werden.  Um dieses Problem zu beheben, gehen Sie wie folgt vor:

. Gehen Sie in der Google Cloud Console zu https://console.cloud.google.com/iam-admin/orgpolicies["Seite mit Organisationsrichtlinien"^] Die
. Suchen Sie die Richtlinie *Projektübergreifende Dienstkontonutzung deaktivieren* und deaktivieren Sie sie.


.Wie geht es weiter?
link:task-add-roles.html["Weisen Sie Google Cloud NetApp Volumes Rollen zu"].
